/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TaxiSimulator;
import javax.swing.JOptionPane;

/**
 *
 * @author joseb
 */
public class TaxiOptions extends javax.swing.JFrame {

    /**
     * Creates new form TaxiOptions
     */
    
    private static TaxiSimulator _taxiSimulator;
    
    public TaxiOptions(TaxiSimulator pTaxiSimulator) {
        initComponents();
        _taxiSimulator = pTaxiSimulator;
        setResizable(false);
        setLocationRelativeTo(null);
        setValues();
    }
    
    private void setValues(){
        TFLDClientX.setText("");
        TFLDClientY.setText("");
        TFLDClients.setText("");
        TFLDMS.setText("");
        if(_taxiSimulator.getSleep() == 0){BTNNextMove.setEnabled(true);}
        else{BTNNextMove.setEnabled(false);}
        
        if(_taxiSimulator.isShowTrail()){BTNShowTrail.setText("Hide trail");}
        else{BTNShowTrail.setText("Show trail");}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNTakeARide = new javax.swing.JButton();
        BTNSearch = new javax.swing.JButton();
        BTNShowTrail = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TFLDMS = new javax.swing.JTextField();
        BTNSetMS = new javax.swing.JButton();
        BTNNextMove = new javax.swing.JButton();
        BTNShowTravel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TFLDClients = new javax.swing.JTextField();
        BTNAddClients = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TFLDClientX = new javax.swing.JTextField();
        TFLDClientY = new javax.swing.JTextField();
        BTNAddClient = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Parking = new javax.swing.JTextField();
        BTNPark = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BTNTakeARide.setText("Take a ride");
        BTNTakeARide.setPreferredSize(new java.awt.Dimension(130, 25));
        BTNTakeARide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTakeARideActionPerformed(evt);
            }
        });

        BTNSearch.setText("Search clients");
        BTNSearch.setPreferredSize(new java.awt.Dimension(130, 25));

        BTNShowTrail.setText("Show trail");
        BTNShowTrail.setPreferredSize(new java.awt.Dimension(130, 25));
        BTNShowTrail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNShowTrailActionPerformed(evt);
            }
        });

        jLabel1.setText("Set ms to");

        TFLDMS.setPreferredSize(new java.awt.Dimension(40, 22));

        BTNSetMS.setText("Set");
        BTNSetMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSetMSActionPerformed(evt);
            }
        });

        BTNNextMove.setText("Next Move");
        BTNNextMove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNNextMoveActionPerformed(evt);
            }
        });

        BTNShowTravel.setText("Show Travel");

        jLabel3.setText("Add clients");

        TFLDClients.setText(" ");
        TFLDClients.setPreferredSize(new java.awt.Dimension(40, 22));
        TFLDClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFLDClientsActionPerformed(evt);
            }
        });

        BTNAddClients.setText("OK");
        BTNAddClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAddClientsActionPerformed(evt);
            }
        });

        jLabel4.setText("Add client to");

        TFLDClientX.setText(" ");
        TFLDClientX.setPreferredSize(new java.awt.Dimension(40, 22));
        TFLDClientX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFLDClientXActionPerformed(evt);
            }
        });

        TFLDClientY.setText(" ");
        TFLDClientY.setPreferredSize(new java.awt.Dimension(40, 22));
        TFLDClientY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFLDClientYActionPerformed(evt);
            }
        });

        BTNAddClient.setText("OK");
        BTNAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAddClientActionPerformed(evt);
            }
        });

        jLabel5.setText("Park in");

        Parking.setText(" ");
        Parking.setPreferredSize(new java.awt.Dimension(30, 22));

        BTNPark.setText("OK");
        BTNPark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNParkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(TFLDClientX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TFLDClientY, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTNAddClient))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Parking, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTNPark)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(TFLDClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTNAddClients))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(BTNShowTrail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTNTakeARide, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTNSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(BTNShowTravel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TFLDMS, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(BTNSetMS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNNextMove)
                        .addGap(0, 0, 0))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNTakeARide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNShowTrail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TFLDMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNSetMS)
                    .addComponent(BTNNextMove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNShowTravel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFLDClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNAddClients))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TFLDClientX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFLDClientY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNAddClient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Parking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNPark))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNSetMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSetMSActionPerformed
        if(TFLDMS.getText().matches("[0-9]+")){
            int ms = Integer.parseInt(TFLDMS.getText());
            if(ms>=0){
                _taxiSimulator.setSleep(ms);
            }
            else{
                JOptionPane.showMessageDialog(this,"MS can only be positive.","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"MS can only be numbers.","Error",JOptionPane.ERROR_MESSAGE);
        }
        setValues();
    }//GEN-LAST:event_BTNSetMSActionPerformed

    private void TFLDClientYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFLDClientYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFLDClientYActionPerformed

    private void BTNAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAddClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNAddClientActionPerformed

    private void TFLDClientXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFLDClientXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFLDClientXActionPerformed

    private void TFLDClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFLDClientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFLDClientsActionPerformed

    private void BTNParkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNParkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNParkActionPerformed

    private void BTNTakeARideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTakeARideActionPerformed
        _taxiSimulator.takeARide();
    }//GEN-LAST:event_BTNTakeARideActionPerformed

    private void BTNNextMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNNextMoveActionPerformed
       _taxiSimulator.setContinue(true);
    }//GEN-LAST:event_BTNNextMoveActionPerformed

    private void BTNShowTrailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNShowTrailActionPerformed
        _taxiSimulator.setShowTrail(!_taxiSimulator.isShowTrail());
        setValues();
    }//GEN-LAST:event_BTNShowTrailActionPerformed

    private void BTNAddClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAddClientsActionPerformed
        if(TFLDClients.getText().matches("[0-9]+")){
            int clients = Integer.parseInt(TFLDClients.getText());
            if(clients>0){
                _taxiSimulator.addClients(clients);
            }
            else{
                JOptionPane.showMessageDialog(this,"Clients can't be negative nor zero.","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Clients can only be numbers.","Error",JOptionPane.ERROR_MESSAGE);
        }
        setValues();
    }//GEN-LAST:event_BTNAddClientsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaxiOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaxiOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaxiOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaxiOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaxiSimulator taxiSimulator = null;
                new TaxiOptions(taxiSimulator).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAddClient;
    private javax.swing.JButton BTNAddClients;
    private javax.swing.JButton BTNNextMove;
    private javax.swing.JButton BTNPark;
    private javax.swing.JButton BTNSearch;
    private javax.swing.JButton BTNSetMS;
    private javax.swing.JButton BTNShowTrail;
    private javax.swing.JButton BTNShowTravel;
    private javax.swing.JButton BTNTakeARide;
    private javax.swing.JTextField Parking;
    private javax.swing.JTextField TFLDClientX;
    private javax.swing.JTextField TFLDClientY;
    private javax.swing.JTextField TFLDClients;
    private javax.swing.JTextField TFLDMS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
