/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TaxiSimulator;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author joseb
 */
public class TaxiOptions extends javax.swing.JFrame {

    /**
     * Creates new form TaxiOptions
     */
    
    private TaxiSimulator _taxiSimulator;
    
    public TaxiOptions(TaxiSimulator pTaxiSimulator) {
        initComponents();
        _taxiSimulator = pTaxiSimulator;
        setResizable(false);
        setLocationRelativeTo(null);
        LBLName.setText("Taxi: "+_taxiSimulator.getTaxiName());
        setValues();
    }
    
    private void setValues(){
        LBLMS.setText("Actual MS:" + _taxiSimulator.getSleep());
        if(_taxiSimulator.getSleep() == 0){BTNNextMove.setEnabled(true);}
        else{BTNNextMove.setEnabled(false);}
        
        if(_taxiSimulator.isShowTrail()){BTNShowTrail.setText("Hide trail");}
        else{BTNShowTrail.setText("Show trail");}
        
        if(_taxiSimulator.isShowTravel()){BTNShowTravel.setText("Hide travel");}
        else{BTNShowTravel.setText("Show travel");}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNTakeARide = new javax.swing.JButton();
        BTNSearch = new javax.swing.JButton();
        BTNShowTrail = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TFLDMS = new javax.swing.JTextField();
        BTNSetMS = new javax.swing.JButton();
        BTNNextMove = new javax.swing.JButton();
        BTNShowTravel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TFLDClients = new javax.swing.JTextField();
        BTNAddClients = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TFLDClientX = new javax.swing.JTextField();
        TFLDClientY = new javax.swing.JTextField();
        BTNAddClient = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TFLDParking = new javax.swing.JTextField();
        BTNPark = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LBLMS = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TFLDGotoX = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TFLDGotoY = new javax.swing.JTextField();
        BTNGoto = new javax.swing.JButton();
        LBLName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BTNTakeARide.setText("Take a ride");
        BTNTakeARide.setPreferredSize(new java.awt.Dimension(130, 25));
        BTNTakeARide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTakeARideActionPerformed(evt);
            }
        });

        BTNSearch.setText("Search clients");
        BTNSearch.setPreferredSize(new java.awt.Dimension(130, 25));
        BTNSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSearchActionPerformed(evt);
            }
        });

        BTNShowTrail.setText("Show trail");
        BTNShowTrail.setPreferredSize(new java.awt.Dimension(130, 25));
        BTNShowTrail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNShowTrailActionPerformed(evt);
            }
        });

        jLabel1.setText("Set ms to");

        TFLDMS.setPreferredSize(new java.awt.Dimension(40, 22));
        TFLDMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFLDMSActionPerformed(evt);
            }
        });
        TFLDMS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFLDMSKeyPressed(evt);
            }
        });

        BTNSetMS.setText("Set");
        BTNSetMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSetMSActionPerformed(evt);
            }
        });

        BTNNextMove.setText("Next Move");
        BTNNextMove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNNextMoveActionPerformed(evt);
            }
        });

        BTNShowTravel.setText("Show Travel");
        BTNShowTravel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNShowTravelActionPerformed(evt);
            }
        });

        jLabel3.setText("Add clients");

        TFLDClients.setPreferredSize(new java.awt.Dimension(40, 22));
        TFLDClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFLDClientsActionPerformed(evt);
            }
        });
        TFLDClients.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFLDClientsKeyPressed(evt);
            }
        });

        BTNAddClients.setText("OK");
        BTNAddClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAddClientsActionPerformed(evt);
            }
        });

        jLabel4.setText("Add client to");

        TFLDClientX.setMinimumSize(new java.awt.Dimension(40, 22));
        TFLDClientX.setPreferredSize(new java.awt.Dimension(40, 22));
        TFLDClientX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFLDClientXActionPerformed(evt);
            }
        });
        TFLDClientX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFLDClientXKeyPressed(evt);
            }
        });

        TFLDClientY.setMinimumSize(new java.awt.Dimension(40, 22));
        TFLDClientY.setPreferredSize(new java.awt.Dimension(40, 22));
        TFLDClientY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFLDClientYActionPerformed(evt);
            }
        });
        TFLDClientY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFLDClientYKeyPressed(evt);
            }
        });

        BTNAddClient.setText("OK");
        BTNAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAddClientActionPerformed(evt);
            }
        });

        jLabel5.setText("Park in");

        TFLDParking.setPreferredSize(new java.awt.Dimension(30, 22));
        TFLDParking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFLDParkingActionPerformed(evt);
            }
        });
        TFLDParking.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFLDParkingKeyPressed(evt);
            }
        });

        BTNPark.setText("OK");
        BTNPark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNParkActionPerformed(evt);
            }
        });

        jLabel2.setText("x");

        jLabel6.setText("y");

        LBLMS.setText("Actual ms:");

        jLabel7.setText("Go to:");

        jLabel8.setText("x");

        TFLDGotoX.setMinimumSize(new java.awt.Dimension(40, 22));
        TFLDGotoX.setPreferredSize(new java.awt.Dimension(40, 22));
        TFLDGotoX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFLDGotoXKeyPressed(evt);
            }
        });

        jLabel9.setText("y");

        TFLDGotoY.setMinimumSize(new java.awt.Dimension(40, 22));
        TFLDGotoY.setPreferredSize(new java.awt.Dimension(40, 22));
        TFLDGotoY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFLDGotoYKeyPressed(evt);
            }
        });

        BTNGoto.setText("OK");
        BTNGoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGotoActionPerformed(evt);
            }
        });

        LBLName.setText("Taxi:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(BTNShowTrail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BTNTakeARide, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BTNSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LBLMS))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BTNShowTravel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TFLDClientX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TFLDClientY, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BTNAddClient))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TFLDClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BTNAddClients)))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TFLDMS, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(BTNSetMS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNNextMove)
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(4, 4, 4)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TFLDParking, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BTNPark))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TFLDGotoX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TFLDGotoY, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BTNGoto))))
                            .addComponent(LBLName))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(LBLName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNTakeARide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLMS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNShowTrail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BTNSetMS)
                    .addComponent(BTNNextMove)
                    .addComponent(TFLDMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNShowTravel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFLDClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNAddClients))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TFLDClientX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFLDClientY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNAddClient)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TFLDParking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNPark))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(TFLDGotoX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(TFLDGotoY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNGoto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNSetMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSetMSActionPerformed
        if(TFLDMS.getText().matches("[0-9]+")){
            int ms = Integer.parseInt(TFLDMS.getText());
            if(ms>=0){
                _taxiSimulator.setSleep(ms);
                TFLDMS.setText("");
            }
            else{
                JOptionPane.showMessageDialog(this,"MS can only be positive.","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"MS can only be numbers.","Error",JOptionPane.ERROR_MESSAGE);
        }
        setValues();
    }//GEN-LAST:event_BTNSetMSActionPerformed

    private void TFLDClientYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFLDClientYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFLDClientYActionPerformed

    private void BTNAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAddClientActionPerformed
        if(TFLDClientX.getText().matches("[0-9]+")){
            int X = Integer.parseInt(TFLDClientX.getText());
            if(X>=0){
                if(TFLDClientY.getText().matches("[0-9]+")){
                    int Y = Integer.parseInt(TFLDClientY.getText());
                    if(Y>=0){
                        /*
                        
                        int resp = _taxiSimulator.addClient(X, Y);
                        if(resp == -1){
                            JOptionPane.showMessageDialog(this,"There's something in ("+X+","+Y+").","Error",JOptionPane.ERROR_MESSAGE);
                        }
                        else if(resp == -2){
                            JOptionPane.showMessageDialog(this,"That's an invalid position.","Error",JOptionPane.ERROR_MESSAGE);
                        }
                        else{
                            TFLDClientX.setText("");
                            TFLDClientY.setText("");
                            setValues();
                        }
                        */
                    }
                    else{
                        JOptionPane.showMessageDialog(this,"Y can only be positive.","Error",JOptionPane.ERROR_MESSAGE);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this,"Y can only be numbers.","Error",JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"X can only be positive.","Error",JOptionPane.ERROR_MESSAGE);
            }
            
        }
        else{
            JOptionPane.showMessageDialog(this,"X can only be numbers.","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BTNAddClientActionPerformed

    private void TFLDClientXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFLDClientXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFLDClientXActionPerformed

    private void TFLDClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFLDClientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFLDClientsActionPerformed

    private void BTNParkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNParkActionPerformed
        if(!TFLDParking.getText().equals("")){
            int resp = _taxiSimulator.parkIn(TFLDParking.getText());
            if(resp == -1){
                JOptionPane.showMessageDialog(this,"'" + TFLDParking.getText() + "' doesn't exist.","Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                TFLDParking.setText("");
            }
        }
    }//GEN-LAST:event_BTNParkActionPerformed

    private void BTNTakeARideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTakeARideActionPerformed
        _taxiSimulator.takeARide();
    }//GEN-LAST:event_BTNTakeARideActionPerformed

    private void BTNNextMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNNextMoveActionPerformed
       _taxiSimulator.setContinue(true);
    }//GEN-LAST:event_BTNNextMoveActionPerformed

    private void BTNShowTrailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNShowTrailActionPerformed
        _taxiSimulator.setShowTrail(!_taxiSimulator.isShowTrail());
        setValues();
    }//GEN-LAST:event_BTNShowTrailActionPerformed

    private void BTNAddClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAddClientsActionPerformed
        if(TFLDClients.getText().matches("[0-9]+")){
            int clients = Integer.parseInt(TFLDClients.getText());
            if(clients>0){
                //_taxiSimulator.addClients(clients);
                TFLDClients.setText("");
            }
            else{
                JOptionPane.showMessageDialog(this,"Clients can't be negative nor zero.","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Clients can only be numbers.","Error",JOptionPane.ERROR_MESSAGE);
        }
        setValues();
    }//GEN-LAST:event_BTNAddClientsActionPerformed

    private void BTNSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSearchActionPerformed
        _taxiSimulator.searchClients();
    }//GEN-LAST:event_BTNSearchActionPerformed

    private void BTNShowTravelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNShowTravelActionPerformed
        _taxiSimulator.setShowTravel(!_taxiSimulator.isShowTravel());
        setValues();
    }//GEN-LAST:event_BTNShowTravelActionPerformed

    private void TFLDMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFLDMSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFLDMSActionPerformed

    private void TFLDParkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFLDParkingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFLDParkingActionPerformed

    private void BTNGotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGotoActionPerformed
        if(TFLDGotoX.getText().matches("[0-9]+")){
            int X = Integer.parseInt(TFLDGotoX.getText());
            if(X>=0){
                if(TFLDGotoY.getText().matches("[0-9]+")){
                    int Y = Integer.parseInt(TFLDGotoY.getText());
                    if(Y>=0){
                        int resp = _taxiSimulator.goTo(X, Y);
                        if(resp == -1){
                            JOptionPane.showMessageDialog(this,"Invalid point on ("+X+","+Y+").","Error",JOptionPane.ERROR_MESSAGE);
                        }
                        else{
                            TFLDGotoX.setText("");
                            TFLDGotoY.setText("");
                            setValues();
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this,"Y can only be positive.","Error",JOptionPane.ERROR_MESSAGE);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this,"Y can only be numbers.","Error",JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"X can only be positive.","Error",JOptionPane.ERROR_MESSAGE);
            }
            
        }
        else{
            JOptionPane.showMessageDialog(this,"X can only be numbers.","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BTNGotoActionPerformed

    private void TFLDMSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFLDMSKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BTNSetMSActionPerformed(null);
        }
    }//GEN-LAST:event_TFLDMSKeyPressed

    private void TFLDClientsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFLDClientsKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BTNAddClientsActionPerformed(null);
        }
    }//GEN-LAST:event_TFLDClientsKeyPressed

    private void TFLDClientXKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFLDClientXKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BTNAddClientActionPerformed(null);
        }
    }//GEN-LAST:event_TFLDClientXKeyPressed

    private void TFLDClientYKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFLDClientYKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BTNAddClientActionPerformed(null);
        }
    }//GEN-LAST:event_TFLDClientYKeyPressed

    private void TFLDParkingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFLDParkingKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BTNParkActionPerformed(null);
        }
    }//GEN-LAST:event_TFLDParkingKeyPressed

    private void TFLDGotoXKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFLDGotoXKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BTNGotoActionPerformed(null);
        }
    }//GEN-LAST:event_TFLDGotoXKeyPressed

    private void TFLDGotoYKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFLDGotoYKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BTNGotoActionPerformed(null);
        }
    }//GEN-LAST:event_TFLDGotoYKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaxiOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaxiOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaxiOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaxiOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaxiOptions(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAddClient;
    private javax.swing.JButton BTNAddClients;
    private javax.swing.JButton BTNGoto;
    private javax.swing.JButton BTNNextMove;
    private javax.swing.JButton BTNPark;
    private javax.swing.JButton BTNSearch;
    private javax.swing.JButton BTNSetMS;
    private javax.swing.JButton BTNShowTrail;
    private javax.swing.JButton BTNShowTravel;
    private javax.swing.JButton BTNTakeARide;
    private javax.swing.JLabel LBLMS;
    private javax.swing.JLabel LBLName;
    private javax.swing.JTextField TFLDClientX;
    private javax.swing.JTextField TFLDClientY;
    private javax.swing.JTextField TFLDClients;
    private javax.swing.JTextField TFLDGotoX;
    private javax.swing.JTextField TFLDGotoY;
    private javax.swing.JTextField TFLDMS;
    private javax.swing.JTextField TFLDParking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
